---
language: ruby
rvm:
  - "2.2.0"

sudo: false
cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-favicon --check-html --disable-external

notifications:
  email: false
  slack:
    secure: "K2vpcVkpNL0R3Iv9DA4bqNTuCidvMvKnP9HGmM7jc3Ng4w6iFDFQ+DZJbkPnSFXKcW0rHRFoFtTaxTNvCC6ZAlDgdL9NOlNvt6P7krI2fHrMpIJ9RaPhfpgVxtkfJIRvCMP+est+iMEFkici55wHMy20mdaV1GM9HWr3XkOMqRE="
