---
language: ruby
rvm:
- "2.3.0"

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
- gem install bundler -v 1.13.6

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external

notifications:
  email: false
  slack:
    secure: "K2vpcVkpNL0R3Iv9DA4bqNTuCidvMvKnP9HGmM7jc3Ng4w6iFDFQ+DZJbkPnSFXKcW0rHRFoFtTaxTNvCC6ZAlDgdL9NOlNvt6P7krI2fHrMpIJ9RaPhfpgVxtkfJIRvCMP+est+iMEFkici55wHMy20mdaV1GM9HWr3XkOMqRE="
