include:
  - _pages

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: tomasbasham
      type: "BlogPosting"
      comments: true

# Site settings
title: Tomas Basham's Blog
description: Tomas Basham's Personal Technology Jekyll Blog and Development Portfolio
author: tomasbasham
lang: en_GB
url: https://tomasbasham.dev
cover: https://cdn.tomasbasham.dev/covers/remote.jpg

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination settings
paginate: 8
paginate_path: "/page:num/"

# Sass settings
sass:
  style: compressed
  load_paths:
    - vendor

# Analytics settings
analytics:
  google_tracking_id: UA-51944071-1

# Disqus settings
comments:
  disqus_shortname: tomasbasham

# GitHub settings
github:
  owner_email: tomasbasham@gmail.com

# Twitter settings
twitter:
  username: tomasbahsam

# Social profiles
social:
  name: Tomas Basham
  links:
    - https://twitter.com/tomasbasham
    - https://github.com/tomasbasham
    - https://www.linkedin.com/in/tomas-basham-06244646
