exclude: [vendor]

gems:
  - jemoji
  - jekyll-github-metadata
  - jekyll-sitemap

# Site settings
title: Tomas Basham
email: me@tomasbasham.co.uk
description: A Personal Jekyll Blog and Portfolio
bio: Technical Director at a fast growing statup company.
baseurl: ""
url: "http://tomasbasham.co.uk" # the base hostname & protocol for your site
repository: tomasbasham/tomasbasham.github.io
twitter_username: tomasbasham
github_username: tomasbasham

# Build settings
markdown: redcarpet
highlighter: pygments

# blog cover
cover: //cdn.tomasbasham.co.uk/cover.jpg

paginate:	5

analytics:
  google_tracking_id: UA-51944071-1

comments:
  disqus_shortname: tomasbasham

# social icons and sharing options
social:
  - icon:	twitter
    url: https://twitter.com/tomasbasham
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url: https://facebook.com/tomasbasham
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	google-plus
    url: https://google.com/+TomasBasham
    desc:	Add me on google+
    share_url: https://plus.google.com/share
    share_title: ?t=
    share_link: "&amp;url="

  - icon:	github
    url: https://github.com/tomasbasham
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: rss
    url: http://tomasbasham.co.uk/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:
