exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

gems:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Site settings
title: Tomas Basham
description: A Personal Jekyll Blog and Portfolio
url: "https://tomasbasham.co.uk" # the base hostname & protocol for your site

# Personal settings
bio: Technical Director at a fast growing statup company.
email: me@tomasbasham.co.uk
repository: tomasbasham/tomasbasham.github.io

# Build settings
markdown: kramdown
highlighter: rouge

# Blog cover
cover: https://cdn.tomasbasham.co.uk/cover.jpg

# Pagination settings
paginate: 8
paginate_path: "/page:num/"

# Disqus settings
comments:
  disqus_shortname: tomasbasham

# Analytics settings
analytics:
  google_tracking_id: UA-51944071-1

# Social icons and sharing options
social:
  share:
    - icon: facebook
      share_url: https://www.facebook.com/sharer.php
      share_title: "?t="
      share_link: "&amp;u="

    - icon: google-plus
      share_url: https://plus.google.com/share
      share_title: "?t="
      share_link: "&amp;url="

    - icon: linkedin
      share_url: https://www.linkedin.com/shareArticle
      share_title: "?title="
      share_link: "&amp;mini=true&amp;url="

    - icon: twitter
      share_url: https://twitter.com/share
      share_title: "?text="
      share_link: "&amp;url="

  accounts:
    - name: GitHub
      url: https://github.com/tomasbasham
      desc:	Fork me on github

    - name: Linkedin
      url: https://www.linkedin.com/in/tomas-basham-06244646
      desc: Connect with me linkedin

    - name: Twitter
      url: https://twitter.com/tomasbasham
      desc: Follow me on twitter

    - name: RSS
      url: https://tomasbasham.co.uk/feed.xml
      desc: Subscribe
